import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import NavigasiDasboardVar1 from "@/app/components/navigasi_bar/navigasi_var_1";
import { UserService } from "@/backend/services/userService";


const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "CMS Dashboard",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await UserService.getDataUserLogin();


  return (
    <html lang="en" className="h-full antialiased">
      <body className={`${plusJakartaSans.className} min-h-full flex flex-col bg-slate-50`}>
        <NavigasiDasboardVar1 role={user?.role} />
        {children}
      </body>
    </html>
  );
}
